blog/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from . import views


app_name = 'blog'

urlpatterns = [
    path('home/', views.HomePageView.as_view(), name='index'),
    path('', views.HomePageView.as_view(), name='index'),
    path('account/register/', TemplateView.as_view(template_name='registration/registration.html'), name='register'),
    path('account/register/validate/', views.validate_new_user, name='validate'),
    path('blogs/', views.BlogListView.as_view(), name='blogs'),
    path('blog/<int:pk>/', views.BlogDetailView.as_view(), name='detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author'),
    path('<int:pk>/create_comment/', views.CreateCommentView.as_view(), name='create_comment'),
    path('<int:post_id>/add_comment/', views.add_comment, name='add_comment'),
]

urlpatterns += [
    path('account/', include('django.contrib.auth.urls'))
]

just_a_blog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class BlogPost(models.Model):
    class Meta:
        ordering = ['pub_date']

    def __str__(self):
        return self.name

    name = models.CharField(max_length=50)
    author = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    pub_date = models.DateTimeField(timezone.now())
    content = models.TextField()


class Comment(models.Model):
    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.comment_text

    blog = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    author = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    pub_date = models.DateTimeField(timezone.now())
    comment_text = models.CharField(max_length=300)

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, reverse
from django.views.generic import DetailView, ListView, TemplateView
from django.utils import timezone
from django.contrib.auth.views import login_required
from django.utils.decorators import method_decorator

from .models import BlogPost, Comment, User


@method_decorator(login_required, name='dispatch')
class HomePageView(TemplateView):
    template_name = 'blog/index.html'


class BlogListView(ListView):
    model = BlogPost
    context_object_name = 'ordered_posts'
    paginate_by = 5
    template_name = 'blog/blogs.html'

    def get_queryset(self):
        return BlogPost.objects.filter(pub_date__lte=timezone.now())


class BlogDetailView(DetailView):
    model = BlogPost
    template_name = 'blog/detail.html'


class CreateCommentView(DetailView):
    model = BlogPost
    template_name = 'blog/create_comment.html'


def add_comment(rq, post_id):
    try:
        post = get_object_or_404(BlogPost, pk=post_id)
    except (post.DoesNotExist, KeyError):
        return render(rq, 'blog/create_comment.html', {
            'post_id': post_id,
            'error_message': 'Post is not exist'
        })
    else:
        comment = Comment.objects.create(blog_id=post_id,
                                         author=rq.user.profile,
                                         comment_text=rq.POST['comment-text'],
                                         pub_date=timezone.now())
        comment.save()
        return HttpResponseRedirect(reverse('blog:detail', args=(post_id,)))


def validate_new_user(rq):
    if User.objects.filter(username=rq.POST['username']).first():
        return render(rq, 'blog/../templates/registration/registration.html', {
            'error_message': 'Username has already been taken.'
        })
    elif len(rq.POST['password']) < 6:
        return render(rq, 'blog/../templates/registration/registration.html', {
            'error_message': 'Password must contain at least 6 symbols.'
        })
    elif User.objects.filter(email=rq.POST['email']).first():
        return render(rq, 'blog/../templates/registration/registration.html', {
            'error_message': 'Email has already been registered.'
        })
    else:
        user = User.objects.create_user(
            rq.POST['username'],
            rq.POST['email'],
            rq.POST['password'],
        )

        user.save()
        return HttpResponseRedirect(reverse('blog:index'))


class AuthorListView(ListView):
    model = User
    template_name = 'blog/authors.html'


class AuthorDetailView(TemplateView):
    template_name = 'blog/author.html'

blog/templates/blog/author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{% extends 'blog/base_generic.html' %}
    <title>Title</title>
</head>
<body>
{% block content %}
    <h1>Author {{ user.username }} info</h1>
    <p><strong>Biography</strong></p>
    <p>{{ user.profile.bio }}</p>
    <br>
    <p><strong>Latest author blog posts</strong></p>
    <ul>
    {% for post in user.profile.blogpost_set.all|slice:"5" %}
        <li>
            <a href="{% url 'blog:detail' post.id %}">{{ post.name }}</a>
            - ({{ post.pub_date }})
        </li>
    {% endfor %}
    </ul>
{% endblock %}
</body>
</html>

blog/templates/blog/authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends 'blog/base_generic.html' %}
    <title>Title</title>
</head>
<body>
{% block content %}
    <h1>All bloggers</h1>
    <ul class="author-list">
    {% for user in user_list  %}
        <li><a href="{% url 'blog:author' user.id %}">{{ user.username }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}
</body>
</html>

blog/templates/blog/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     {% block title %}<title>Just a blog</title>{% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    {% load compress static %}
    {% compress css %}
    <link rel="stylesheet" type="text/less" href="{% static 'blog/styles/styles.less' %}">
    {% endcompress %}
</head>
<body>
    <div class="wrapper">
        <div class="col-sm-2">
        {% block sidebar %}
            <aside class="sidebar">
                <nav class="routes">
                    <a href="{% url 'blog:index' %}">Home</a>
                    <a href="{% url 'blog:blogs' %}">All blogs</a>
                    <a href="{% url 'blog:authors' %}">All authors</a>
                </nav>
                <br>
                <div class="auth-info">
                {% if user.is_authenticated %}
                    <span class="username">
                        User:
                        {{ user.username }}
                    </span>
                    <a href="{% url 'blog:logout' %}">
                        Выйти из системы.
                    </a>
                {% else %}
                    <span class="username">
                        User:
                         anonymous
                    </span>
                    <a href="{% url 'blog:login' %}">
                        Войти в систему
                    </a>
                {% endif %}
                </div>
            </aside>
        {% endblock %}
        </div>
        <div class="col-sm-10">
        {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

blog/templates/blog/base_generic_account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{% block title %}<title>Just a blog</title>{% endblock %}
{% load compress static %}
{% compress css %}
    <link rel="stylesheet" type="text/less" href="{% static 'blog/styles/account.less' %}">
{% endcompress %}
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

blog/templates/blog/blogs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="blog_list">
        <h1>All blogs</h1>
        <ul>
        {% for post in ordered_posts %}
            <li>
                <a href="{% url 'blog:detail' post.id %}">{{ post.name }}</a>
                <span>({{ post.pub_date }}) - </span>
                <a href="{% url 'blog:author' post.author.id %}">{{ post.author }}</a>
            </li>
        {% endfor %}
        </ul>
    </div>
    <div class="pagination">
        <span class="link-steps">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; 1</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

            <span class="current_page">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">
                {{ page_obj.paginator.num_pages }} &raquo;
            </a>
        {% endif %}
        </span>
    </div>

</body>
</html>

blog/templates/blog/create_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends 'blog/base_generic.html' %}
    <title>Title</title>
</head>
<body>
{% block content %}
    <p class="post-name">
        Post your comment for
        <a href="{% url 'blog:detail' blogpost.id %}">{{ blogpost.name }}</a>
    </p>
    <form action="{% url 'blog:add_comment' blogpost.id %}" class="create-comment" method="post">
    {% csrf_token %}
        <div class="create-comment__desc">
            <p class="desc__title"><strong>Description:</strong></p>
            <div class="desc__content">
                <textarea name="comment-text" id="comment-text" cols="40" rows="10" required></textarea>
                <p>Enter your comment about blog here</p>
            </div>
        </div>
        <input type="submit" class="create-comment__submit" value="Submit">
    </form>

{% endblock %}
</body>
</html>

blog/templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends 'blog/base_generic.html' %}
    <title>Title</title>
</head>
<body>
{% block content %}
    <div class="post-info">
        <h1>{{ blogpost.name }}</h1>
        <p><strong>Post date </strong>{{ blogpost.pub_date }}</p>
        <p><strong>Author </strong>{{ blogpost.author }}</p>
        <p><strong>Description</strong></p>
        <br>
        <p>{{ blogpost.content }}</p>
    </div>
        <div class="post-comments">
            <p class="post-comments__title">Comments</p>
        {% for comment in blogpost.comment_set.all %}
            <div class="post-comments__comment">
                {{ comment.author }} ({{ comment.pub_date }}) - {{ comment.comment_text }}
            </div>
        {% endfor %}
            <div class="post-comments__link">
        {% if user.is_authenticated %}
            <a href="{% url 'blog:create_comment' blogpost.id %}"
               class="post-comments__comment">Add a new comment
            </a>
        {% else %}
                <p>You must log in to add a comment</p>
                <a href="{% url 'blog:login' %}"
                   id="login">Login</a>
        {% endif %}
            </div>
        </div>
{% endblock %}
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends 'blog/base_generic.html' %}
    <title>Home</title>
</head>
<body>
{% if author.is_authenticated %}
{% block content %}
    <h1>Welcome page</h1>
{% endblock  %}
{% endif %}
</body>
</html>